global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cross-checker
    metrics_path: /metrics
    static_configs:
      - targets: [graphix-cross-checker:9184]
