{
 "title": "Graphix Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "deployments",
     "endTimePath": "endTime",
     "queryText": "query {\n deployments(filter: {}) { id\n networkName\n name\n   }\n}"
    }
   ]
  },
  {
   "title": "Success rate of \"indexingStatuses\" by indexer, over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (indexer)(rate(indexing_statuses_requests{success=\"1\"}[$__rate_interval])) / sum by (indexer)(rate(indexing_statuses_requests[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate of \"publicProofsOfIndexing\" by indexer, over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "rate(public_proofs_of_indexing_requests{success=\"1\"}[$__rate_interval]) / rate(public_proofs_of_indexing_requests[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of monitored indexers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "indexers",
     "endTimePath": "endTime",
     "queryText": "query {\n indexers(filter: {}) {\n id\n }\n}"
    }
   ]
  },
  {
   "title": "RPS: \"publicProofsOfIndexing\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum (rate(public_proofs_of_indexing_requests[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}